# Generated by Django 5.0.14 on 2026-09-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_app_and_stk_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='app_approval_required',
            field=models.BooleanField(default=False, help_text='When on, approvers must enter their separate 6-digit approval password in the app before a payment is sent.'),
        ),
    ]
