# Generated by Django 5.0.14 on 2026-09-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appsettings_app_approval_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='stk_pin_approval_required',
            field=models.BooleanField(default=False, help_text='When on, approvers must confirm on a registered phone (and approval password) before the hub paybill sends the payout. Legacy Lipa STK charge is off by default.'),
        ),
    ]
