# Generated by Django 5.0.14 on 2026-09-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_approval_guest_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalguesttoken',
            new_name='core_approv_user_id_9fb133_idx',
            old_name='core_approv_guest_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalsmschallenge',
            new_name='core_approv_user_id_589164_idx',
            old_name='core_approv_user_id_6a8f2d_idx',
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='stk_pin_approval_required',
            field=models.BooleanField(default=False, help_text='When on, approvers need a registered phone and their hub approval password before the paybill sends the payout (no M-Pesa charge on the reviewer phone by default).'),
        ),
    ]
