# Generated by Django 5.0.14 on 2026-09-19 14:24

import accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employeesalary_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_requests', accounts.fields.MysqlBooleanEnumField(default=False)),
                ('review_requests', accounts.fields.MysqlBooleanEnumField(default=False)),
                ('manage_people', accounts.fields.MysqlBooleanEnumField(default=False)),
                ('manage_hr', accounts.fields.MysqlBooleanEnumField(default=False)),
                ('manage_ledger', accounts.fields.MysqlBooleanEnumField(default=False)),
                ('manage_daraja', accounts.fields.MysqlBooleanEnumField(default=False)),
                ('view_hub_balance', accounts.fields.MysqlBooleanEnumField(default=False)),
                ('manage_integrations', accounts.fields.MysqlBooleanEnumField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee permissions',
                'verbose_name_plural': 'employee permissions',
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _seed_permissions(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _seed_permissions(apps):
    User = apps.get_model("accounts", "User")
    EmployeePermissions = apps.get_model("accounts", "EmployeePermissions")
    role_defaults = {
        "PENDING_APPROVAL": {},
        "CLIENT": {},
        "EMPLOYEE": {"submit_requests": True},
        "ACCOUNTS": {
            "review_requests": True,
            "manage_ledger": True,
            "view_hub_balance": True,
        },
        "IT_SUPPORT": {
            "review_requests": True,
            "manage_hr": True,
            "manage_ledger": True,
            "manage_daraja": True,
            "view_hub_balance": True,
            "manage_integrations": True,
        },
        "MANAGER": {
            "review_requests": True,
            "manage_people": True,
            "manage_hr": True,
            "manage_ledger": True,
            "manage_daraja": True,
            "view_hub_balance": True,
        },
        "ADMIN": {
            "submit_requests": True,
            "review_requests": True,
            "manage_people": True,
            "manage_hr": True,
            "manage_ledger": True,
            "manage_daraja": True,
            "view_hub_balance": True,
            "manage_integrations": True,
        },
    }
    for user in User.objects.exclude(role__in=["CLIENT", "PENDING_APPROVAL"]):
        defaults = role_defaults.get(user.role, {})
        EmployeePermissions.objects.get_or_create(
            user=user,
            defaults={
                "submit_requests": defaults.get("submit_requests", False),
                "review_requests": defaults.get("review_requests", False),
                "manage_people": defaults.get("manage_people", False),
                "manage_hr": defaults.get("manage_hr", False),
                "manage_ledger": defaults.get("manage_ledger", False),
                "manage_daraja": defaults.get("manage_daraja", False),
                "view_hub_balance": defaults.get("view_hub_balance", False),
                "manage_integrations": defaults.get("manage_integrations", False),
            },
        )
