# Generated by Django 6.1.1 on 2026-09-13 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaybillAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paybill_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=160)),
                ('provider', models.CharField(choices=[('MPESA', 'M-Pesa'), ('AIRTEL', 'Airtel Money'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='MPESA', max_length=20)),
                ('short_code_notes', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connected_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paybill_accounts', to='paybill.connectedsystem')),
            ],
            options={
                'ordering': ['account_name'],
                'unique_together': {('paybill_number', 'connected_system')},
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('direction', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], default='IN', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('payer_name', models.CharField(blank=True, max_length=160)),
                ('payer_phone', models.CharField(blank=True, max_length=20)),
                ('account_ref', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=16)),
                ('narrative', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('connected_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='paybill.connectedsystem')),
                ('paybill_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='paybill.paybillaccount')),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['posted_at'], name='paybill_led_posted__3652b2_idx'), models.Index(fields=['status'], name='paybill_led_status_126862_idx')],
            },
        ),
    ]
