# Generated by Django 5.0.14 on 2026-09-15 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TRAVEL', 'Travel'), ('OFFICE', 'Office supplies'), ('UTILITIES', 'Utilities'), ('MEALS', 'Meals & entertainment'), ('CLIENT', 'Client / project'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], max_length=20)),
                ('destination_type', models.CharField(choices=[('PAYBILL', 'Paybill'), ('TILL', 'Till (Buy Goods)'), ('PHONE', 'Phone number')], max_length=12)),
                ('destination', models.CharField(max_length=20)),
                ('account_ref', models.CharField(blank=True, help_text='Account number when sending to a paybill.', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_requests', to=settings.AUTH_USER_MODEL)),
                ('source_paybill', models.ForeignKey(help_text='Hub paybill the funds should come from.', on_delete=django.db.models.deletion.PROTECT, related_name='money_requests', to='paybill.paybillaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
