# Generated by Django 5.0.14 on 2026-09-15 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_money_request_review_fields'),
        ('paybill', '0002_money_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrequest',
            name='daraja_operation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_request', to='integrations.darajaoperation'),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_money_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
