# Generated by Django 5.0.14 on 2026-09-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0003_money_request_review_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='mpesa_reference',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa receipt / transaction reference when provided by Safaricom.', max_length=64),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='mpesa_reference',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa receipt / transaction reference after payout succeeds.', max_length=64),
        ),
    ]
