# Generated by Django 5.0.14 on 2026-09-15 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0005_backfill_mpesa_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='expense_category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='expense_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='money_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='paybill.moneyrequest'),
        ),
    ]
