# Generated by Django 5.0.14 on 2026-09-15 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0007_backfill_money_request_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrequest',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='When a reviewer opened this request. Status stays Pending.', null=True),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='viewed_by',
            field=models.ForeignKey(blank=True, help_text='Reviewer who opened this request in the app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_money_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
