# Generated by Django 5.0.14 on 2026-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0008_money_request_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
    ]
