# Generated by Django 5.0.14 on 2026-09-26 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0010_money_request_recipient_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('account_type', models.CharField(choices=[('PAYBILL', 'Paybill'), ('TILL', 'Till'), ('PHONE', 'Phone number')], max_length=12)),
                ('identifier', models.CharField(help_text='Paybill, till, or MSISDN (254…).', max_length=20)),
                ('account_ref', models.CharField(blank=True, help_text='Optional paybill account number for ledger filtering.', max_length=64)),
                ('auto_refresh', models.BooleanField(default=True, help_text='Periodically request live balance from Safaricom when Daraja balance is configured.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_monitors', to=settings.AUTH_USER_MODEL)),
                ('paybill_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_monitors', to='paybill.paybillaccount')),
            ],
            options={
                'ordering': ['label', 'identifier'],
            },
        ),
        migrations.AddConstraint(
            model_name='collectionmonitor',
            constraint=models.UniqueConstraint(fields=('account_type', 'identifier', 'account_ref'), name='uniq_collection_monitor_target'),
        ),
    ]
