# Generated by Django 5.0.14 on 2026-09-26 12:01

import django.db.models.deletion
import secrets
from django.db import migrations, models


def backfill_collection_codes(apps, schema_editor):
    CollectionMonitor = apps.get_model("paybill", "CollectionMonitor")
    used: set[str] = set()
    for row in CollectionMonitor.objects.all().order_by("pk"):
        if (row.collection_code or "").strip():
            used.add(row.collection_code.strip())
            continue
        for _ in range(32):
            code = ("C" + secrets.token_hex(5).upper())[:12]
            if code not in used and not CollectionMonitor.objects.filter(collection_code=code).exists():
                row.collection_code = code
                row.save(update_fields=["collection_code"])
                used.add(code)
                break


class Migration(migrations.Migration):

    dependencies = [
        ("paybill", "0011_collection_monitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionmonitor",
            name="collection_code",
            field=models.CharField(
                blank=True,
                help_text="Unique STK/C2B reference for this account (auto-generated).",
                max_length=12,
            ),
        ),
        migrations.RunPython(backfill_collection_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="collectionmonitor",
            name="collection_code",
            field=models.CharField(
                blank=True,
                help_text="Unique STK/C2B reference for this account (auto-generated).",
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="collectionmonitor",
            name="daraja_consumer_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="collectionmonitor",
            name="daraja_consumer_secret",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="collectionmonitor",
            name="daraja_passkey",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="collectionmonitor",
            name="daraja_shortcode",
            field=models.CharField(
                blank=True,
                help_text="Lipa shortcode for STK password when this account uses its own Daraja app.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="collectionmonitor",
            name="use_hub_daraja",
            field=models.BooleanField(
                default=True,
                help_text="Use hub Daraja STK credentials; turn off to paste this account's own consumer key/secret.",
            ),
        ),
        migrations.CreateModel(
            name="CollectionMonitorCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="primary", max_length=80)),
                ("key_prefix", models.CharField(max_length=12)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="paybill.collectionmonitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
