# Generated by Django 5.0.14 on 2026-09-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybill', '0014_monitor_payout_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmonitor',
            name='auto_payout_phone',
            field=models.CharField(blank=True, help_text='Legacy phone field; synced with auto_payout_destination for phone payouts.', max_length=20),
        ),
    ]
