# Generated by Django 5.0.14 on 2026-09-14 07:21

import accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('paybill', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DarajaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', accounts.fields.MysqlChoiceEnumField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Production')], default='SANDBOX', max_length=12)),
                ('consumer_key', models.CharField(blank=True, max_length=255)),
                ('consumer_secret', models.CharField(blank=True, max_length=512)),
                ('shortcode', models.CharField(blank=True, help_text='Your Lipa Na M-Pesa paybill / organization shortcode.', max_length=20)),
                ('passkey', models.CharField(blank=True, max_length=512)),
                ('stk_callback_url', models.URLField(blank=True, max_length=500)),
                ('initiator_name', models.CharField(blank=True, max_length=120)),
                ('security_credential', models.TextField(blank=True)),
                ('result_url', models.URLField(blank=True, max_length=500)),
                ('timeout_url', models.URLField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paybill_account', models.ForeignKey(blank=True, help_text='Hub paybill this Daraja app collects into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daraja_configs', to='paybill.paybillaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daraja_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daraja setup',
                'verbose_name_plural': 'Daraja setup',
            },
        ),
    ]
