# Generated by Django 5.0.14 on 2026-09-14 07:34

import accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_daraja_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='darajaconfig',
            name='b2b_enabled',
            field=accounts.fields.MysqlBooleanEnumField(default=False),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='b2b_paybill_command',
            field=accounts.fields.MysqlChoiceEnumField(choices=[('BusinessPayBill', 'Send to paybill (BusinessPayBill)'), ('BusinessBuyGoods', 'Send to till (BusinessBuyGoods)'), ('DisburseFundsToBusiness', 'Disburse to business'), ('BusinessToBusinessTransfer', 'Business to business transfer')], default='BusinessPayBill', max_length=32),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='b2b_remarks',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='b2b_sender_identifier_type',
            field=accounts.fields.MysqlChoiceEnumField(choices=[('1', 'Phone number (MSISDN)'), ('2', 'Till number'), ('4', 'Paybill / organization shortcode')], default='4', max_length=2),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='b2b_till_command',
            field=accounts.fields.MysqlChoiceEnumField(choices=[('BusinessPayBill', 'Send to paybill (BusinessPayBill)'), ('BusinessBuyGoods', 'Send to till (BusinessBuyGoods)'), ('DisburseFundsToBusiness', 'Disburse to business'), ('BusinessToBusinessTransfer', 'Business to business transfer')], default='BusinessBuyGoods', max_length=32),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='b2c_command_id',
            field=accounts.fields.MysqlChoiceEnumField(choices=[('BusinessPayment', 'Business payment'), ('SalaryPayment', 'Salary payment'), ('PromotionPayment', 'Promotion payment')], default='BusinessPayment', max_length=32),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='b2c_enabled',
            field=accounts.fields.MysqlBooleanEnumField(default=False),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='b2c_occasion',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='b2c_remarks',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='balance_identifier_type',
            field=accounts.fields.MysqlChoiceEnumField(choices=[('1', 'Phone number (MSISDN)'), ('2', 'Till number'), ('4', 'Paybill / organization shortcode')], default='4', max_length=2),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='balance_remarks',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='stk_account_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='stk_transaction_desc',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='stk_transaction_type',
            field=accounts.fields.MysqlChoiceEnumField(choices=[('CustomerPayBillOnline', 'Paybill (CustomerPayBillOnline)'), ('CustomerBuyGoodsOnline', 'Till / Buy Goods (CustomerBuyGoodsOnline)')], default='CustomerPayBillOnline', max_length=32),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='till_number',
            field=models.CharField(blank=True, help_text='Buy Goods till, if different from the paybill shortcode.', max_length=20),
        ),
    ]
