# Generated by Django 5.0.14 on 2026-09-14 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_daraja_stk_balance_payout_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DarajaOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STK', 'STK push'), ('BALANCE', 'Account balance'), ('B2C', 'Send to phone'), ('B2B', 'Send to paybill or till')], max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timed out')], default='QUEUED', max_length=16)),
                ('destination', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('account_ref', models.CharField(blank=True, max_length=64)),
                ('merchant_request_id', models.CharField(blank=True, max_length=64)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('originator_conversation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('result_code', models.CharField(blank=True, max_length=16)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daraja_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
