# Generated by Django 5.0.14 on 2026-09-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_daraja_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="darajaconfig",
            name="org_shortcode",
            field=models.CharField(
                blank=True,
                help_text="Organization shortcode for account balance, B2C, and B2B. Sandbox Shortcode 1 is 600986.",
                max_length=20,
            ),
        ),
    ]
