# Generated by Django 5.0.14 on 2026-09-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_daraja_safaricom_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darajaconfig',
            name='org_shortcode',
            field=models.CharField(blank=True, help_text='Organization shortcode for account balance, B2C, and B2B. Sandbox Party A / Shortcode 1 is 600996.', max_length=20),
        ),
    ]
