# Generated by Django 5.0.14 on 2026-09-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_mpesa_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='darajaconfig',
            name='c2b_registration_log',
            field=models.TextField(blank=True, help_text='Last C2B URL registration result from the automations page.'),
        ),
        migrations.AddField(
            model_name='darajaconfig',
            name='c2b_response_type',
            field=models.CharField(default='Completed', help_text='Safaricom C2B ResponseType: Completed accepts after validation; Cancelled can reject on validation URL.', max_length=16),
        ),
    ]
