# Generated by Django 5.0.14 on 2026-09-26 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_daraja_c2b_fields'),
        ('paybill', '0012_monitor_collection_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='darajaoperation',
            name='collection_monitor',
            field=models.ForeignKey(blank=True, help_text='Automation account when this STK push collects on a unique reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daraja_operations', to='paybill.collectionmonitor'),
        ),
    ]
